name: ldm
channels:
  - apple
  - conda-forge
  - pytorch-nightly
  - defaults
dependencies:
  - python=3.10.4
  - pip=22.1.2
  - pytorch
  - torchvision
  - numpy=1.23.1
  - pip:
      - nb-cli
      - volcengine
      - albumentations==0.4.6
      - diffusers
      - opencv-python==4.6.0.66
      - pudb==2019.2
      - invisible-watermark
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.2
      - pytorch-lightning==1.4.2
      - omegaconf==2.1.1
      - test-tube>=0.7.5
      - streamlit>=0.73.1
      - einops==0.3.0
      - torch-fidelity==0.3.0
      - transformers==4.19.2
      - torchmetrics==0.6.0
      - kornia==0.6
      - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
      - -e git+https://github.com/openai/CLIP.git@main#egg=clip
      - -e .
